# Report Docker *host* utilization statistics
#

# Use phusion/baseimage as base image.
FROM phusion/baseimage:0.9.17
MAINTAINER  pitrho

# Set up the environment
#
ENV DEBIAN_FRONTEND noninteractive

# Install build deps
#
RUN apt-get update && apt-get -y -q install \
	bc && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy reporter script
#
COPY reporter.sh /reporter.sh

# Default to reporting CPU, Memory, Disk Space every 5 seconds
#
ENTRYPOINT ["/reporter.sh"]
CMD ["-cmd", "-f", "5"]
