# Report (log to stdout) host statistics
#

# Use phusion/baseimage as base image.
FROM phusion/baseimage:0.9.17
MAINTAINER  pitrho

# Set up the environment
#
ENV DEBIAN_FRONTEND noninteractive

# Install build deps
#
RUN apt-get update && apt-get -y -q install \
	python \
    python-dev \
    python-distribute \
    python-pip \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install pyCLI==2.0.3 psutil==4.2.0 fstab==1.4

# Copy logger script
#
COPY host-stats-logger.py /host-stats-logger.py

# Set up GO environment
#RUN curl -O https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
#RUN tar -xvf go1.6.linux-amd64.tar.gz
#RUN mv go /usr/local

#go get -d github.com/google/cadvisor && cd $GOPATH/github.com/google/cadvisor && make build && sudo ./cadvisor --logtostderr -->

# Default to reporting every 30 seconds
#
ENTRYPOINT ["python", "/host-stats-logger.py"]
CMD ["-f", "30", "-cmdn"]
